version: "4"

services:
  nats-server:
    image: nats:latest

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  # products-ms:
  #   build: ./products-ms
  #   volumes:
  #     - ./products-ms/src:/usr/src/app/src
  #   command: npm run start:dev
  #   environment:
  #     - PORT=3001
  #     - DATABASE_URL=file:./dev.db
  #     - NATS_SERVERS=nats://nats-server:4222

  # auth-db:
  #   container_name: auth-db
  #   image: postgres:16.2
  #   restart: always
  #   volumes:
  #     - ./auth-ms/postgres:/var/lib/postgresql/data
  #   ports:
  #     - ${AUTH_DATABASE_PORT}:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=123456
  #     - POSTGRES_DB=auth-db

  # # Orders DB
  # orders-db:
  #   container_name: orders_database
  #   image: postgres:16.2
  #   restart: always
  #   volumes:
  #     - ./orders-ms/postgres:/var/lib/postgresql/data
  #   ports:
  #     - ${ORDERS_DATABASE_PORT}:${ORDERS_DATABASE_PORT}
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=123456
  #     - POSTGRES_DB=ordersdb

  # # Orders MS
  # orders-ms:
  #   depends_on:
  #     - orders-db
  #   build: ./orders-ms
  #   volumes:
  #     - ./orders-ms/src:/usr/src/app/src
  #   command: npm run start:dev
  #   environment:
  #     - PORT=3002
  #     - DATABASE_URL=${ORDERS_DATABASE_URL}
  #     - NATS_SERVERS=nats://nats-server:4222

  # # ============================================
  # # PAYMENTS - MS
  # # ============================================
  # payments-ms:
  #   container_name: payments-ms
  #   build: ./payments-ms
  #   volumes:
  #     - ./payments-ms/src:/usr/src/app/src
  #   ports:
  #     - ${PAYMENT_MS_PORT}:${PAYMENT_MS_PORT}
  #   command: npm run start:dev
  #   environment:
  #     - PORT=${PAYMENT_MS_PORT}
  #     - NATS_SERVERS=nats://nats-server:4222
  #     - STRIPE_SECRET=${STRIPE_SECRET}
  #     - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
  #     - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
  #     - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}

  # # Auth MS
  # auth-ms:
  #   depends_on:
  #     - auth-db
  #   container_name: auth-ms
  #   build: ./auth-ms
  #   volumes:
  #     - ./auth-ms/src:/usr/src/app/src
  #   command: npm run start:dev
  #   environment:
  #     - PORT=3004
  #     - NATS_SERVERS=nats://nats-server:4222
  #     - DATABASE_URL=${AUTH_DATABASE_URL}
  #     - JWT_SECRET=${JWT_SECRET}
